/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Curso;
import fatec.poo.model.Instrutor;
import fatec.poo.model.Turma;
import java.util.ArrayList;

/**
 *
 * @author Gustavo
 */
public class GuiAlocarInstrutor extends javax.swing.JFrame {

    public GuiAlocarInstrutor(ArrayList<Curso> cadCurso, ArrayList<Turma> cadTurma, ArrayList<Instrutor> cadInstrutor) {

        Instrutores = cadInstrutor;
        
        ArrayList<String> relCursos;

        initComponents();

        relCursos = Curso.listarCursos(cadCurso);
        for (int x = 0; x < relCursos.size(); x++) {
            cboxCurso.addItem(relCursos.get(x));
        }
        //https://stackoverflow.com/questions/18435992/java-call-object-methods-through-arraylist
        for (int i = 0; i < cadTurma.size(); i++) {
            //popula o cbox acessando o metodo getsigla de cada objeto dentro da colection sem precisar de um "listarTurma"
            cboxTurma.addItem(cadTurma.get(i).getSiglaTurma());
        }
        for (int i = 0; i < cadInstrutor.size(); i++) {
            cboxInstrutor.addItem(cadInstrutor.get(i).getNome());
        }

    }

//Instanciando os objetos nessa classe
    private ArrayList<Instrutor> Instrutores;
    private ArrayList<Curso> Cursos;
    private ArrayList<Turma> Turmas;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Curso = new javax.swing.JLabel();
        label_Turma = new javax.swing.JLabel();
        cboxCurso = new javax.swing.JComboBox<>();
        label_Instrutor = new javax.swing.JLabel();
        label_Situacao = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        btnLiberar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        cboxInstrutor = new javax.swing.JComboBox<>();
        cboxTurma = new javax.swing.JComboBox<>();
        txtEndereco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alocar Instrutor");

        label_Curso.setText("Curso");

        label_Turma.setText("Turma");

        cboxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCursoActionPerformed(evt);
            }
        });

        label_Instrutor.setText("Instrutor");

        label_Situacao.setText("Situação");

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        btnInserir.setText("Alocar");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnLiberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnLiberar.setText("Liberar");
        btnLiberar.setEnabled(false);
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        cboxInstrutor.setEnabled(false);
        cboxInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxInstrutorActionPerformed(evt);
            }
        });

        cboxTurma.setEnabled(false);
        cboxTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTurmaActionPerformed(evt);
            }
        });

        txtEndereco.setEditable(false);
        txtEndereco.setEnabled(false);
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(btnInserir)
                        .addGap(18, 18, 18)
                        .addComponent(btnLiberar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label_Instrutor)
                                    .addComponent(label_Turma)
                                    .addComponent(label_Curso))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cboxCurso, javax.swing.GroupLayout.Alignment.LEADING, 0, 106, Short.MAX_VALUE)
                                        .addComponent(cboxTurma, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_Situacao)
                                .addGap(18, 18, 18)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnInserir, btnLiberar, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Curso)
                    .addComponent(cboxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Turma)
                    .addComponent(cboxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Instrutor)
                    .addComponent(cboxInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Situacao)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSair)
                    .addComponent(btnInserir)
                    .addComponent(btnLiberar))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnInserir, btnLiberar, btnSair});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        // estabelecida a associação binária entre os objetos da classe Turma e da classe instrutor.
        
        //pega o instrutor correspondente do arraylist ao selecionado no combobox e associa
        //a turma correspondente do arraylist selecionada no combobox
        
        Instrutores.get(cboxInstrutor.getSelectedIndex()).addTurma(Turmas.get(cboxTurma.getSelectedIndex()));
        txtEndereco.setText("Alocada");
        
        
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void cboxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCursoActionPerformed
        cboxTurma.setEnabled(true);
        cboxInstrutor.setEnabled(true);
    }//GEN-LAST:event_cboxCursoActionPerformed

    private void cboxTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxTurmaActionPerformed

    private void cboxInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxInstrutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxInstrutorActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
        
        Turmas.get(cboxTurma.getSelectedIndex()).setInstrutor(null);
        txtEndereco.setText("Liberada");
    }//GEN-LAST:event_btnLiberarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cboxCurso;
    private javax.swing.JComboBox<String> cboxInstrutor;
    private javax.swing.JComboBox<String> cboxTurma;
    private javax.swing.JLabel label_Curso;
    private javax.swing.JLabel label_Instrutor;
    private javax.swing.JLabel label_Situacao;
    private javax.swing.JLabel label_Turma;
    private javax.swing.JTextField txtEndereco;
    // End of variables declaration//GEN-END:variables

}
