/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Pessoa;
import fatec.poo.model.Aluno;
import fatec.poo.model.ValidarCPF;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class GuiAluno extends javax.swing.JFrame {

    /**
     * Creates new form GuiInstrutor
     */
    public GuiAluno(ArrayList<Pessoa> cadAlunoInstrutor) {
        initComponents();
        
        cadastroP = cadAlunoInstrutor;
        
        //Adicionando Itens na jcomboBox
        cboxSexo.addItem("M");//0
        cboxSexo.addItem("F");//1
        
        cboxEstadoCivil.addItem("Casado");//0
        cboxEstadoCivil.addItem("Solteiro");//1
        cboxEstadoCivil.addItem("Viuvo");//2
        
        cboxEscolaridade.addItem("Fundamental");//0
        cboxEscolaridade.addItem("Medio");//1
        cboxEscolaridade.addItem("Avançado");//2
      
        cboxEstado.addItem("SP");
        cboxEstado.addItem("RJ");
        cboxEstado.addItem("ES");
        cboxEstado.addItem("MG");
        cboxEstado.addItem("AC");
        cboxEstado.addItem("GO");
    }
   
    private ArrayList<Pessoa> cadastroP;
    private int posAluno;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnSair = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JTextField();
        cboxSexo = new javax.swing.JComboBox<>();
        txtBairro = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cboxEstado = new javax.swing.JComboBox<>();
        txtRG = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        cboxEstadoCivil = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTelRes = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        cboxEscolaridade = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Aluno");

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Consultar.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Remover.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel1.setText("CPF");

        jLabel2.setText("Nome");

        jLabel3.setText("Sexo");

        jLabel4.setText("Endereço");

        jLabel5.setText("Cidade");

        jLabel6.setText("Bairro");

        jLabel7.setText("RG");

        jLabel9.setText("Email");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });

        txtNome.setEnabled(false);

        cboxSexo.setEnabled(false);
        cboxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxSexoActionPerformed(evt);
            }
        });

        txtBairro.setEnabled(false);
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });

        txtEndereco.setEnabled(false);
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        txtCidade.setEnabled(false);

        jLabel10.setText("Estado");

        cboxEstado.setEnabled(false);
        cboxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxEstadoActionPerformed(evt);
            }
        });

        try {
            txtRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRG.setEnabled(false);

        txtEmail.setEnabled(false);

        jLabel11.setText("Data Nascimento");

        jLabel12.setText("Escolaridade");

        jLabel13.setText("Nº");

        txtNumero.setEnabled(false);
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascimento.setEnabled(false);
        txtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascimentoActionPerformed(evt);
            }
        });

        cboxEstadoCivil.setEnabled(false);
        cboxEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxEstadoCivilActionPerformed(evt);
            }
        });

        jLabel14.setText("CEP");

        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEP.setEnabled(false);

        jLabel15.setText("Tel. Res");

        try {
            txtTelRes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelRes.setEnabled(false);
        txtTelRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelResActionPerformed(evt);
            }
        });

        jLabel16.setText("Celular");

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # - ########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular.setEnabled(false);

        cboxEscolaridade.setEnabled(false);
        cboxEscolaridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxEscolaridadeActionPerformed(evt);
            }
        });

        jLabel18.setText("Estado Civil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome)
                            .addComponent(txtEndereco)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtBairro)
                            .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel13)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(txtCEP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCelular, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtTelRes))))
                                .addGap(66, 66, 66))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnInserir)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair)
                        .addGap(0, 93, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cboxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(cboxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(cboxEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14)
                            .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSair)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
  
        Pessoa pessoa = new Pessoa(txtCPF.getText(), txtNome.getText());
        Aluno aluno = new Aluno(cboxEscolaridade.getSelectedItem().toString(), "1");
        pessoa.setSexo(cboxSexo.getSelectedItem().toString());
        pessoa.setBairro(txtBairro.getText());
        pessoa.setEndereco(txtEndereco.getText());
        pessoa.setEstado(cboxEstado.getSelectedItem().toString());
        pessoa.setEstadoCivil(cboxEstadoCivil.getSelectedItem().toString());
        pessoa.setRG(txtRG.getText());
        pessoa.setEmail(txtEmail.getText());
        pessoa.setCEP(txtCEP.getText());
        pessoa.setCelular(txtCelular.getText());
        pessoa.setCidade(txtCidade.getText());
        pessoa.setDataNasc(txtDataNascimento.getText());
        pessoa.setNumero(Integer.parseInt(txtNumero.getText()));
        pessoa.setTelefone(txtTelRes.getText());
        pessoa.setCelular(txtCelular.getText());
        
        cadastroP.add(pessoa);
        cadastroP.add(aluno);
        
        //limpando
        txtCPF.setText(null);
        txtNome.setText(null);
        cboxEscolaridade.setSelectedIndex(0);
        cboxEstadoCivil.setSelectedIndex(0);
        txtCelular.setText(null);
        txtTelRes.setText(null);
        txtNumero.setText(null);
        txtDataNascimento.setText(null);
        txtCidade.setText(null);
        txtCelular.setText(null);
        txtCEP.setText(null);
        txtEmail.setText(null);
        txtRG.setText(null);
        cboxEstado.setSelectedIndex(0);
        txtEndereco.setText(null);
        txtBairro.setText(null);
        cboxSexo.setSelectedIndex(0);
        
        //focando
        txtCPF.setEnabled(true);
        txtCPF.requestFocus();
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        
        //bloquando
        txtNome.setEnabled(false);
        cboxEstadoCivil.setEnabled(false);
        cboxEscolaridade.setEnabled(false);
        txtCelular.setEnabled(false);
        txtTelRes.setEnabled(false);
        txtNumero.setEnabled(false);
        txtDataNascimento.setEnabled(false);
        txtCidade.setEnabled(false);
        txtCelular.setEnabled(false);
        txtCEP.setEnabled(false);;
        txtEmail.setEnabled(false);
        txtRG.setEnabled(false);
        cboxEstado.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtBairro.setEnabled(false);
        cboxSexo.setEnabled(false);
        
    }//GEN-LAST:event_btnInserirActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtTelResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelResActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int x;
        String CPF;
        CPF = txtCPF.getText();
        CPF = CPF.replaceAll("[^\\d]", "");

        if (ValidarCPF.vCPF(CPF) == true) {

            for (x = 0; x < cadastroP.size(); x++) {
                if (cadastroP.get(x).getCPF().equals(txtCPF.getText())) {
                    break;
                }
            }

            if (x < cadastroP.size()) {
                posAluno = x;
            } else {
                posAluno = -1;
            }

            if (posAluno >= 0) {
                
                txtNome.setText(cadastroP.get(posAluno).getNome());
                cboxSexo.setSelectedItem(cadastroP.get(posAluno).getSexo());//sexo
                cboxEstadoCivil.setSelectedItem(cadastroP.get(posAluno).getEstadoCivil());//estadoCivil
                txtEndereco.setText(cadastroP.get(posAluno).getEndereco());
                txtBairro.setText(cadastroP.get(posAluno).getBairro());
                txtCidade.setText(cadastroP.get(posAluno).getCidade());
                cboxEstado.setSelectedItem(cadastroP.get(posAluno).getEstado());//estado
                txtRG.setText(cadastroP.get(posAluno).getRG());
                txtEmail.setText(cadastroP.get(posAluno).getEmail());
                txtDataNascimento.setText(String.valueOf(cadastroP.get(posAluno).getDataNasc()));
                //escolaridade
                txtNumero.setText(String.valueOf(cadastroP.get(posAluno).getNumero()));
                txtCEP.setText(cadastroP.get(posAluno).getCEP());
                txtTelRes.setText(cadastroP.get(posAluno).getTelefone());
                txtCelular.setText(cadastroP.get(posAluno).getCelular());

                btnConsultar.setEnabled(false);
                btnInserir.setEnabled(false);
                btnAlterar.setEnabled(true);
                btnExcluir.setEnabled(true);
                txtCPF.setEnabled(false);
                
                txtNome.setEnabled(true);
                cboxEstadoCivil.setEnabled(true);
                cboxEscolaridade.setEnabled(true);
                txtCelular.setEnabled(true);
                txtTelRes.setEnabled(true);
                txtNumero.setEnabled(true);
                txtDataNascimento.setEnabled(true);
                txtCidade.setEnabled(true);
                txtCelular.setEnabled(true);
                txtCEP.setEnabled(true);;
                txtEmail.setEnabled(true);
                txtRG.setEnabled(true);
                cboxEstado.setEnabled(true);
                txtEndereco.setEnabled(true);
                txtBairro.setEnabled(true);
                cboxSexo.setEnabled(true);
                
                txtNome.requestFocus();

            } else {

                btnConsultar.setEnabled(false);
                btnInserir.setEnabled(true);
                btnAlterar.setEnabled(false);
                btnExcluir.setEnabled(false);
                txtCPF.setEnabled(false);
                
                cboxSexo.setEnabled(true);
                cboxEstadoCivil.setEnabled(true);
                cboxEscolaridade.setEnabled(true);
                txtNome.requestFocus();
                txtNome.setEnabled(true);
                txtEndereco.setEnabled(true);
                txtBairro.setEnabled(true);
                txtCidade.setEnabled(true);
                txtRG.setEnabled(true);
                txtEmail.setEnabled(true);
                txtDataNascimento.setEnabled(true);
                txtNumero.setEnabled(true);
                txtCEP.setEnabled(true);
                txtTelRes.setEnabled(true);
                txtCelular.setEnabled(true);
                cboxEstado.setEnabled(true);
                
                txtNome.requestFocus();
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"CPF INVALIDO","ERRO",JOptionPane.WARNING_MESSAGE);
            txtCPF.requestFocus(true);
        }
        
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        cadastroP.get(posAluno).setNome(txtNome.getText());
        cadastroP.get(posAluno).setEstadoCivil(String.valueOf(cboxEstadoCivil.getSelectedItem()));
        cadastroP.get(posAluno).setEstado(String.valueOf(cboxEstado.getSelectedItem()));
        cadastroP.get(posAluno).setCelular(txtCelular.getText());
        cadastroP.get(posAluno).setTelefone(txtTelRes.getText());
        cadastroP.get(posAluno).setNumero(Integer.parseInt(txtNumero.getText()));
        cadastroP.get(posAluno).setDataNasc(txtDataNascimento.getText());
        cadastroP.get(posAluno).setCidade(txtCidade.getText());
        cadastroP.get(posAluno).setCelular(txtCelular.getText());
        cadastroP.get(posAluno).setCEP(txtCEP.getText());
        cadastroP.get(posAluno).setEmail(txtEmail.getText());
        cadastroP.get(posAluno).setRG(txtRG.getText());
        cadastroP.get(posAluno).setEstado(String.valueOf(cboxEstado.getSelectedItem()));
        cadastroP.get(posAluno).setEndereco(txtEndereco.getText());
        cadastroP.get(posAluno).setBairro(txtBairro.getText());
        cadastroP.get(posAluno).setSexo(String.valueOf(cboxSexo.getSelectedItem()));
        
        txtCPF.setText(null);
        txtNome.setText(null);
        cboxEscolaridade.setSelectedIndex(0);
        cboxEstadoCivil.setSelectedIndex(0);
        txtCelular.setText(null);
        txtTelRes.setText(null);
        txtNumero.setText(null);
        txtDataNascimento.setText(null);
        txtCidade.setText(null);
        txtCelular.setText(null);
        txtCEP.setText(null);
        txtEmail.setText(null);
        txtRG.setText(null);
        cboxEstado.setSelectedIndex(0);
        txtEndereco.setText(null);
        txtBairro.setText(null);
        cboxSexo.setSelectedIndex(0);
                
        txtNome.setEnabled(false);
        cboxEstadoCivil.setEnabled(false);
        cboxEscolaridade.setEnabled(false);
        txtCelular.setEnabled(false);
        txtTelRes.setEnabled(false);
        txtNumero.setEnabled(false);
        txtDataNascimento.setEnabled(false);
        txtCidade.setEnabled(false);
        txtCelular.setEnabled(false);
        txtCEP.setEnabled(false);;
        txtEmail.setEnabled(false);
        txtRG.setEnabled(false);
        cboxEstado.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtBairro.setEnabled(false);
        cboxSexo.setEnabled(false);
        
        txtCPF.setEnabled(true);
        btnConsultar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtCPF.requestFocus();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void cboxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxSexoActionPerformed

    private void cboxEscolaridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxEscolaridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxEscolaridadeActionPerformed

    private void cboxEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxEstadoCivilActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_cboxEstadoCivilActionPerformed

    private void cboxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxEstadoActionPerformed

    private void txtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        if(posAluno >= 0){
            cadastroP.remove(posAluno);
            posAluno = -1;          
        }
        
        txtCPF.setText(null);
        txtNome.setText(null);
        cboxEscolaridade.setSelectedIndex(0);
        cboxEstadoCivil.setSelectedIndex(0);
        txtCelular.setText(null);
        txtTelRes.setText(null);
        txtNumero.setText(null);
        txtDataNascimento.setText(null);
        txtCidade.setText(null);
        txtCelular.setText(null);
        txtCEP.setText(null);
        txtEmail.setText(null);
        txtRG.setText(null);
        cboxEstado.setSelectedIndex(0);
        txtEndereco.setText(null);
        txtBairro.setText(null);
        cboxSexo.setSelectedIndex(0);
                
        txtNome.setEnabled(false);
        cboxEstadoCivil.setEnabled(false);
        cboxEscolaridade.setEnabled(false);
        txtCelular.setEnabled(false);
        txtTelRes.setEnabled(false);
        txtNumero.setEnabled(false);
        txtDataNascimento.setEnabled(false);
        txtCidade.setEnabled(false);
        txtCelular.setEnabled(false);
        txtCEP.setEnabled(false);;
        txtEmail.setEnabled(false);
        txtRG.setEnabled(false);
        cboxEstado.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtBairro.setEnabled(false);
        cboxSexo.setEnabled(false);
        
        txtCPF.setEnabled(true);
        btnConsultar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtCPF.requestFocus();
    }//GEN-LAST:event_btnExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cboxEscolaridade;
    private javax.swing.JComboBox<String> cboxEstado;
    private javax.swing.JComboBox<String> cboxEstadoCivil;
    private javax.swing.JComboBox<String> cboxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JFormattedTextField txtRG;
    private javax.swing.JFormattedTextField txtTelRes;
    // End of variables declaration//GEN-END:variables



}

