/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.APrazo;
import fatec.poo.model.AVista;
import fatec.poo.model.Curso;
import fatec.poo.model.Matricula;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Turma;
import fatec.poo.model.ValidarCPF;
import java.util.ArrayList;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class GuiEfetuarMatricula extends javax.swing.JFrame {

    /**
     * Creates new form GuiInstrutor
     */
    public GuiEfetuarMatricula(ArrayList<Curso> cadCurso, ArrayList<Turma> cadTurma, 
            ArrayList<Pessoa> cadAlunoInstrutor, ArrayList<Matricula> cadMatricula, 
            ArrayList<APrazo> cadAPrazo, ArrayList<AVista> cadAVista) {
        initComponents();
        int x;
        
        cadastroC = cadCurso;
        cadastroT = cadTurma;
        cadastroP = cadAlunoInstrutor;
        cadastroM = cadMatricula;
        cadastroAPrazo = cadAPrazo;
        cadastroAVista = cadAVista;
        
        if(cadastroC.size() != 0){
            for (x = 0; x < cadastroC.size(); x++){
                if (cadastroC == null){
                    break;
                }
                cboxCurso.addItem(cadastroC.get(x).getSigla());
            }
        }
        
        if(cadastroT.size() != 0){
            for (x = 0; x < cadastroT.size(); x++){
                if (cadastroT == null){
                    break;
                }
                cboxTurma.addItem(cadastroT.get(x).getSiglaTurma());
            }
        }

        cboxCurso.setEnabled(true); //CURSO
        cboxTurma.setEnabled(true); //turma
        
        //A VISTA
        rbtnVista.setEnabled(false);
        
        //A Prazo
        rbtnParcelado.setEnabled(false);
        
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        
        txtDataMatricu.setText(String.valueOf(dateFormat.format(date)));
        
        txtCPFAluno.setEnabled(false);
    }
    
    private ArrayList<Curso> cadastroC;
    private ArrayList<Turma> cadastroT;
    private ArrayList<Pessoa> cadastroP;
    private ArrayList<Matricula> cadastroM;
    private ArrayList<APrazo> cadastroAPrazo;
    private ArrayList<AVista> cadastroAVista;
    private int posAluno;
    private boolean auxCurso = false, auxTurma = false;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnSair = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboxCurso = new javax.swing.JComboBox<>();
        txtNome = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDataMatricu = new javax.swing.JFormattedTextField();
        cboxTurma = new javax.swing.JComboBox<>();
        txtAgencia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCheque = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMensalidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtJuros = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDataPagto = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDataVenci = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        rbtnVista = new javax.swing.JRadioButton();
        rbtnParcelado = new javax.swing.JRadioButton();
        txtCPFAluno = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Efetuar Matrícula");

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Consultar.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Remover.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel2.setText("Curso");

        jLabel3.setText("Turma");

        jLabel4.setText("Nome");

        jLabel7.setText("Cpf Aluno");

        jLabel9.setText("Valor");

        cboxCurso.setEnabled(false);
        cboxCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxCursoItemStateChanged(evt);
            }
        });
        cboxCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboxCursoMouseClicked(evt);
            }
        });
        cboxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCursoActionPerformed(evt);
            }
        });

        txtNome.setEnabled(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtValor.setEnabled(false);
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        jLabel11.setText("Data da Matricula");

        try {
            txtDataMatricu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataMatricu.setEnabled(false);
        txtDataMatricu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataMatricuActionPerformed(evt);
            }
        });

        cboxTurma.setEnabled(false);
        cboxTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboxTurmaMouseClicked(evt);
            }
        });
        cboxTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTurmaActionPerformed(evt);
            }
        });

        txtAgencia.setEnabled(false);
        txtAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgenciaActionPerformed(evt);
            }
        });

        jLabel10.setText("Agência");

        txtCheque.setEnabled(false);
        txtCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChequeActionPerformed(evt);
            }
        });

        jLabel12.setText("no.Cheque");

        txtMensalidade.setEnabled(false);
        txtMensalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensalidadeActionPerformed(evt);
            }
        });

        jLabel13.setText("Qdte. Mensalidades");

        txtJuros.setEnabled(false);
        txtJuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJurosActionPerformed(evt);
            }
        });

        jLabel15.setText("Tx. Juros(%)");

        try {
            txtDataPagto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataPagto.setEnabled(false);
        txtDataPagto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataPagtoActionPerformed(evt);
            }
        });

        jLabel16.setText("Data Pagto.");

        try {
            txtDataVenci.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataVenci.setEnabled(false);
        txtDataVenci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataVenciActionPerformed(evt);
            }
        });

        jLabel17.setText("Data 1o. Vencto.");

        rbtnVista.setText("À vista");
        rbtnVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnVistaActionPerformed(evt);
            }
        });

        rbtnParcelado.setText("Parcelado");
        rbtnParcelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnParceladoActionPerformed(evt);
            }
        });

        try {
            txtCPFAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataMatricu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(btnConsultar)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnInserir)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnAlterar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnExcluir)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnSair))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtDataPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtDataVenci, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbtnVista)
                                        .addComponent(rbtnParcelado))
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(23, 23, 23)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cboxTurma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cboxCurso, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCPFAluno))
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(224, 224, 224))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(46, 46, 46))))
                .addGap(43, 80, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataMatricu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtCPFAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(rbtnVista)
                    .addComponent(jLabel16)
                    .addComponent(txtDataPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(txtDataVenci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(rbtnParcelado)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSair)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
            
            double valorV = Double.parseDouble(txtValor.getText());
            double valorP = Double.parseDouble(txtValor.getText());
            String dataMa = txtDataMatricu.getText();
            dataMa = dataMa.replaceAll("[^\\d]", "");
            
            
            Matricula matricula = new Matricula(txtNome.getText());
            matricula.setData(dataMa);
            
            if(rbtnParcelado.isSelected()){
               AVista avista = new AVista();
               
               avista.setAgencia(Integer.parseInt(txtAgencia.getText()));
               avista.setnCheque(Integer.parseInt(txtCheque.getText()));
               avista.setPreData(txtDataPagto.getText());
               
               avista.setValor(valorP);
                
              
            }
            else if(rbtnVista.isSelected()){
                APrazo aprazo = new APrazo();
                
                aprazo.setQtdeMensalidade(Integer.parseInt(txtMensalidade.getText()));
                aprazo.setTaxaJuros(Double.parseDouble(txtJuros.getText()));
                aprazo.setDtVencimento(txtDataVenci.getText());
                
                valorV = valorV/Integer.parseInt(txtMensalidade.getText());
                valorV = valorV+(valorV * (Double.parseDouble(txtJuros.getText())/100));
                
                aprazo.setValor(valorV);
                
            }// TODO add your handling code here:
    }//GEN-LAST:event_btnInserirActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int x;
        String CPF;
        CPF = txtCPFAluno.getText();
        CPF = CPF.replaceAll("[^\\d]", "");

        if (ValidarCPF.vCPF(CPF) == true) {
            
            for (x = 0; x < cadastroP.size(); x++) {
                if (cadastroP.get(x).getCPF().equals(txtCPFAluno.getText())) {
                    break;
                }
            }

            if (x < cadastroP.size()) {
                posAluno = x;
            } else {
                posAluno = -1;
            }
            
            if (posAluno >= 0) {
                
                txtNome.setText(cadastroP.get(posAluno).getNome());
                btnInserir.setEnabled(true);
                btnConsultar.setEnabled(false);
                txtCPFAluno.setEnabled(false);
              
                
            }
            else{
                JOptionPane.showMessageDialog(null,"CPF NAO ENCONTRADO","AVISO",JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"CPF INVALIDO","AVISO",JOptionPane.ERROR_MESSAGE);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtDataMatricuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataMatricuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataMatricuActionPerformed

    private void cboxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCursoActionPerformed
        String selecionado;
        selecionado = (String)cboxCurso.getSelectedItem();
        int x;
        
        for (x = 0; x < cadastroC.size(); x++){
            if (cadastroC.get(x).getSigla().equals(selecionado)){
                break;
            }
        }
        
        txtValor.setText(String.valueOf(cadastroC.get(x).getValor()));
        
      
       
        
    }//GEN-LAST:event_cboxCursoActionPerformed

    private void cboxTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTurmaActionPerformed
   
    }//GEN-LAST:event_cboxTurmaActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgenciaActionPerformed

    private void rbtnVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnVistaActionPerformed
        if(rbtnVista.isSelected()){
            txtAgencia.setEnabled(true);//agência
            txtCheque.setEnabled(true);//no.cheque
            txtDataPagto.setEnabled(true);//data pagamento
        }
        else{
            txtAgencia.setEnabled(false);//agência
            txtCheque.setEnabled(false);//no.cheque
            txtDataPagto.setEnabled(false);//data pagamento
        }
    }//GEN-LAST:event_rbtnVistaActionPerformed

    private void rbtnParceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnParceladoActionPerformed
        if(rbtnParcelado.isSelected()){
            txtMensalidade.setEnabled(true); //qtde.Menssalidade
            txtJuros.setEnabled(true);// Juros
            txtDataVenci.setEnabled(true);//data vencimento
        }
        else{
            txtMensalidade.setEnabled(false); //qtde.Menssalidade
            txtJuros.setEnabled(false);// Juros
            txtDataVenci.setEnabled(false);//data vencimento
        }
        
    }//GEN-LAST:event_rbtnParceladoActionPerformed

    private void txtChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChequeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChequeActionPerformed

    private void txtDataPagtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataPagtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataPagtoActionPerformed

    private void txtMensalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMensalidadeActionPerformed

    private void txtJurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJurosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJurosActionPerformed

    private void txtDataVenciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataVenciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataVenciActionPerformed

    private void txtCPFAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFAlunoActionPerformed

    private void cboxCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxCursoItemStateChanged

    }//GEN-LAST:event_cboxCursoItemStateChanged

    private void cboxCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboxCursoMouseClicked
       auxCurso = true;
        
        if( auxCurso == true && auxTurma == true){
            txtCPFAluno.setEnabled(true);
            rbtnParcelado.setEnabled(true);
            rbtnVista.setEnabled(true);
        } // TODO add your handling code here:
    }//GEN-LAST:event_cboxCursoMouseClicked

    private void cboxTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboxTurmaMouseClicked
       auxTurma = true;
        
        if( auxCurso == true && auxTurma == true){
            txtCPFAluno.setEnabled(true);
            rbtnParcelado.setEnabled(true);
            rbtnVista.setEnabled(true);
        } // TODO add your handling code here:
    }//GEN-LAST:event_cboxTurmaMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cboxCurso;
    private javax.swing.JComboBox<String> cboxTurma;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbtnParcelado;
    private javax.swing.JRadioButton rbtnVista;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JFormattedTextField txtCPFAluno;
    private javax.swing.JTextField txtCheque;
    private javax.swing.JFormattedTextField txtDataMatricu;
    private javax.swing.JFormattedTextField txtDataPagto;
    private javax.swing.JFormattedTextField txtDataVenci;
    private javax.swing.JTextField txtJuros;
    private javax.swing.JTextField txtMensalidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
