/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Departamento;
import fatec.poo.model.Funcionario;
import fatec.poo.model.FuncionarioComissionado;
import fatec.poo.model.FuncionarioHorista;
import fatec.poo.model.FuncionarioMensalista;
import java.util.ArrayList;

/**
 *
 * @author Dimas
 */
public class GuiFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form GuiFuncionario
     */
    public GuiFuncionario(ArrayList<Funcionario> cadFunc,
                          ArrayList<Departamento> cadDepto){
        String[] relDeptos; 
        
        initComponents();
        cadastroF = cadFunc; 
        cadastroD = cadDepto;
        
        relDeptos = listarDepartamentos();        
        for (int x=0; x < relDeptos.length; x++){
            cbxDepartamento.addItem(relDeptos[x]);
        }        
        lblTaxaComissao.setVisible(false);
        txtTaxaComissao.setVisible(false);
        txtRegistro.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRegistro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDtAdmissao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        cbxTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lblRotulo = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblTaxaComissao = new javax.swing.JLabel();
        txtTaxaComissao = new javax.swing.JTextField();
        cbxDepartamento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Funcionário");

        jLabel1.setText("Registro");

        jLabel2.setText("Nome");

        txtNome.setEnabled(false);

        jLabel3.setText("Data de Admissão");

        txtDtAdmissao.setEnabled(false);

        jLabel4.setText("Cargo");

        txtCargo.setEnabled(false);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Consultar.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Remover.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Horista", "Mensalista", "Comissionado" }));
        cbxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo");

        lblRotulo.setText("Valor Hora");

        txtValor.setEnabled(false);

        lblTaxaComissao.setText("Taxa de Comissão");

        txtTaxaComissao.setEnabled(false);

        cbxDepartamento.setEnabled(false);

        jLabel6.setText("Departamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel5)
                                            .addComponent(lblRotulo)
                                            .addComponent(lblTaxaComissao)
                                            .addComponent(jLabel2))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGap(17, 17, 17)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtTaxaComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cbxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDtAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDtAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRotulo)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxaComissao)
                    .addComponent(txtTaxaComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int x;
        for (x = 0; x < cadastroF.size(); x++){
            if (cadastroF.get(x).getRegistro() == Integer.parseInt(txtRegistro.getText())){
                if (cbxTipo.getSelectedIndex() == 0 && 
                    cadastroF.get(x) instanceof FuncionarioHorista){                       
                       break;
                }else
                  if (cbxTipo.getSelectedIndex() == 1 && 
                      cadastroF.get(x) instanceof FuncionarioMensalista){                      
                      break; 
                  }else 
                      if (cbxTipo.getSelectedIndex() == 2 && 
                          cadastroF.get(x) instanceof FuncionarioComissionado){
                          break; 
                  } 
            }
        }

        if (x < cadastroF.size()){
            posFunc = x; //localizou o objeto Funcionario (horista, mensalista ou comissionado) no ArrayList
        }else{
            posFunc = -1;//não localizou o objeto Projeto no ArrayList
        }

        if (posFunc >= 0){
            txtNome.setText(cadastroF.get(posFunc).getNome());
            txtDtAdmissao.setText(cadastroF.get(posFunc).getDtAdmissao());
            txtCargo.setText(cadastroF.get(posFunc).getCargo());
            if (cbxTipo.getSelectedIndex() == 0){
                txtValor.setText(String.valueOf(((FuncionarioHorista)cadastroF.get(posFunc)).getValHorTrab()));
            }else
               if (cbxTipo.getSelectedIndex() == 1){
                  txtValor.setText(String.valueOf(((FuncionarioMensalista)cadastroF.get(posFunc)).getValSalMin()));
               }else{                  
                  txtValor.setText(String.valueOf(((FuncionarioComissionado)cadastroF.get(posFunc)).getSalBase()));
                  txtTaxaComissao.setText(String.valueOf(((FuncionarioComissionado)cadastroF.get(posFunc)).getTaxaComissao()));
               } 
            
            //Atualizando o ComboBox cbxDepartamento de acordo
            //como o departamento associado
            cbxDepartamento.setSelectedItem(cadastroF.get(posFunc).getDepartamento().getNome());
            
            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
        }else{
            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(true);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
            txtNome.requestFocus();
        }
        cbxTipo.setEnabled(false);
        txtRegistro.setEnabled(false);
        txtNome.setEnabled(true);
        txtDtAdmissao.setEnabled(true);
        txtCargo.setEnabled(true);
        txtValor.setEnabled(true);
        cbxDepartamento.setEnabled(true);
        if (cbxTipo.getSelectedIndex() == 2){
            txtTaxaComissao.setEnabled(true);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
       //instanciação do objeto da classe Funcionario Horista, Mensalista ou Comissionado
       Funcionario func=null; 
       if (cbxTipo.getSelectedIndex() == 0){
           func = new FuncionarioHorista(Integer.parseInt(txtRegistro.getText()),
                                         txtNome.getText(), 
                                         txtDtAdmissao.getText(),
                                         Double.parseDouble(txtValor.getText())); 
       }else 
          if (cbxTipo.getSelectedIndex() == 1){
             func = new FuncionarioMensalista(Integer.parseInt(txtRegistro.getText()),
                                              txtNome.getText(), 
                                              txtDtAdmissao.getText(),
                                              Double.parseDouble(txtValor.getText()));           
        }else  
           if (cbxTipo.getSelectedIndex() == 2){
               func = new FuncionarioComissionado(Integer.parseInt(txtRegistro.getText()),
                                                  txtNome.getText(), 
                                                  txtDtAdmissao.getText(),
                                                  Double.parseDouble(txtTaxaComissao.getText()));            
               ((FuncionarioComissionado)func).setSalBase(Double.parseDouble(txtValor.getText()));
           }      
        func.setCargo(txtCargo.getText());       
       
        //Estabelecendo a associação binária entre um objeto Departamento
        //com um objeto Funcionario (Horista, Mensalista ou Comissionado)
        cadastroD.get(cbxDepartamento.getSelectedIndex()).addFuncionario(func);
        
        //insere o objeto no ArrayList
        cadastroF.add(func); 
        
        txtRegistro.setText(null);
        txtNome.setText(null);
        txtDtAdmissao.setText(null);
        txtCargo.setText(null);
        txtValor.setText(null);
        
        if (cbxTipo.getSelectedIndex() == 2){
           txtTaxaComissao.setText(null);
           txtTaxaComissao.setEnabled(false);
        }
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        cbxTipo.setEnabled(true);
        cbxDepartamento.setEnabled(false);
        txtRegistro.setEnabled(true);
        txtNome.setEnabled(false);
        txtDtAdmissao.setEnabled(false);
        txtCargo.setEnabled(false);
        txtValor.setEnabled(false);
        cbxTipo.setSelectedIndex(0);
        cbxDepartamento.setSelectedIndex(0);
        txtRegistro.requestFocus();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        cbxTipo.setEnabled(false);
        txtRegistro.setEnabled(false);
        cadastroF.get(posFunc).setNome(txtNome.getText());
        cadastroF.get(posFunc).setDtAdmissao(txtDtAdmissao.getText());
        cadastroF.get(posFunc).setCargo(txtCargo.getText());
        
        //verifica se houve a alteração de departamento para o funcionário
        //caso positivo estabelece uma nova associação binária entre
        //Funcionario e Departamento
        if (!(cadastroF.get(posFunc).getDepartamento().getNome()).equals(cbxDepartamento.getSelectedItem())){
            //remove a atual associação binária
            cadastroF.get(posFunc).getDepartamento().removeFuncionario(cadastroF.get(posFunc));
            
            //estabelece a nova associaçã binária
            cadastroD.get(cbxDepartamento.getSelectedIndex()).addFuncionario(cadastroF.get(posFunc));
        }
        
        if (cbxTipo.getSelectedIndex() == 0){
                ((FuncionarioHorista)cadastroF.get(posFunc)).setValHorTrab(Double.parseDouble(txtValor.getText()));
            }else
               if (cbxTipo.getSelectedIndex() == 1){
               ((FuncionarioMensalista)cadastroF.get(posFunc)).setValSalMin(Double.parseDouble(txtValor.getText()));
               }else{
                  txtValor.setText(String.valueOf(((FuncionarioComissionado)cadastroF.get(posFunc)).getSalBase()));
                  ((FuncionarioComissionado)cadastroF.get(posFunc)).setTaxaComissao(Double.parseDouble(txtTaxaComissao.getText()));
               } 

        txtRegistro.setText(null);
        txtNome.setText(null);
        txtDtAdmissao.setText(null);
        txtCargo.setText(null);
        txtValor.setText(null);
        cbxTipo.setSelectedIndex(0);
        cbxDepartamento.setSelectedIndex(0);
        if (cbxTipo.getSelectedIndex() == 2){
           txtTaxaComissao.setText(null);
           txtTaxaComissao.setEnabled(false);
           txtTaxaComissao.setVisible(false);
           lblTaxaComissao.setVisible(false);
        }
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtRegistro.setEnabled(true);
        txtNome.setEnabled(false);
        txtDtAdmissao.setEnabled(false);
        txtCargo.setEnabled(false);
        txtValor.setEnabled(false);
        cbxTipo.setEnabled(true);
        cbxDepartamento.setEnabled(false);
        txtRegistro.requestFocus();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (posFunc >= 0){
            //remove a associação binária entre Funcionario e Departamento
            cadastroF.get(posFunc).getDepartamento().removeFuncionario(cadastroF.get(posFunc));
            cadastroF.remove(posFunc);
            posFunc = -1;
        }
        txtRegistro.setText(null);
        txtNome.setText(null);
        txtDtAdmissao.setText(null);
        txtCargo.setText(null);
        txtValor.setText(null);
        cbxTipo.setSelectedIndex(0);
        cbxDepartamento.setSelectedIndex(0);
        
        if (cbxTipo.getSelectedIndex() == 2){
           txtTaxaComissao.setText(null);
           txtTaxaComissao.setEnabled(false);
           txtTaxaComissao.setVisible(false);
           lblTaxaComissao.setVisible(false);
        }
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        cbxTipo.setEnabled(true);
        cbxDepartamento.setEnabled(false);
        txtRegistro.setEnabled(true);
        txtNome.setEnabled(false);
        txtDtAdmissao.setEnabled(false);
        txtCargo.setEnabled(false);
        txtValor.setEnabled(false);          
        txtRegistro.requestFocus();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void cbxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoActionPerformed
        if (cbxTipo.getSelectedIndex() == 0){
            lblRotulo.setText("Valor Hora");
            lblTaxaComissao.setVisible(false);
            txtTaxaComissao.setVisible(false);
        }else
           if (cbxTipo.getSelectedIndex() == 1){
               lblRotulo.setText("Salário Mínimo");
               lblTaxaComissao.setVisible(false);
               txtTaxaComissao.setVisible(false);
           }else{
               lblRotulo.setText("Salário Base");
               lblTaxaComissao.setVisible(true);
               txtTaxaComissao.setVisible(true); 
           } 
           txtRegistro.requestFocus();
    }//GEN-LAST:event_cbxTipoActionPerformed

    private String[] listarDepartamentos(){
        String[] listaDeptos = new String[cadastroD.size()];
        
        for (int x=0; x < cadastroD.size(); x++){
            listaDeptos[x] = cadastroD.get(x).getNome();
        }
        return listaDeptos;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxDepartamento;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblRotulo;
    private javax.swing.JLabel lblTaxaComissao;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtDtAdmissao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRegistro;
    private javax.swing.JTextField txtTaxaComissao;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Funcionario> cadastroF;
    private ArrayList<Departamento> cadastroD;
    private int posFunc;
}
